hello:
  desc: 打招呼
  key: /hello

help:
  desc: 查看帮助信息
  key: /help

me:
  desc: 查看自己信息
  key: /me

luck:
  desc: 生成0~100随机数
  key: /luck

morning:
  desc: 每日签到
  key: 
    - /morning
    - /checkin

rpi:
  desc: 查看树莓派信息
  key: /rpi
  opt:
    - cpu
    - ram
    - rom
